### PR TITLE
Test portability

### PR DESCRIPTION
**Pull request by johnf**
Make the overall set up of the test suite a little more portable.

### CODE REVIEW

**Comment by arthurnn** [comment]
Thanks for the PR.
When try to test it, I get this error:
```
[arthurnn@ralph lhm]$ bin/lhm-spec-clobber.sh
removing /Users/arthurnn/lhm-cluster
setting up cluster
FATAL ERROR: Could not find ./bin/my_print_defaults

If you compiled from source, you need to run 'make install' to
copy the software into the correct location ready for operation.

If you are using a binary release, you must either be at the top
level of the extracted archive, or pass the --basedir option
pointing to that location.
```

Also, can you squash your commits in one.

**Comment by johnf** [comment]
I've tried a different tack where I set the PATH instead of the location of each binary.

I assume you are on an OS X platform? Do you have a homebrew install?

If it doesn't work I'll try and do some testing on my partners machine and see if I can replicate.

**Comment by arthurnn** [comment]
> I assume you are on an OS X platform? Do you have a homebrew install?

Yes and Yes

**Comment by johnf** [comment]
Closing ancient old open pull requests

**Pull request closed without merging**
