### PR TITLE
Change schema validation to match actual requirement

### PR DESCRIPTION
**Pull request by hannestyden**
The `Chunker` requires an auto incrementing integer column called `id`
to successfully chunk the table while migrating.

### CODE REVIEW

**Comment by hannestyden** [comment]
CI builds fail intermittently due to timing issues and losing connection to the database. Does anyone know how to alleviate those problems? Thanks. :bow:

**Comment by bjk-soundcloud** [comment]
@hannestyden I triggered a rebuild on Travis.  All good now

**Comment by bjk-soundcloud** [comment]
:+1:

**Comment by hannestyden** [comment]
@bjk-soundcloud Thanks a bunch! :bow:

**Comment by hannestyden** [comment]
For some reason all records are not being migrated when the `id` column is not `PRIMARY KEY` even if the `Table#pk` extracted by `Parser#extract_primary_key` seems to be ignored by `Chunker`. Have to investigate more to figure out why.

**Comment by hannestyden** [comment]
False alarm! My test was borked somehow.

The seemingly unused `Parser#extract_primary_key` still worries me though. :worried:

**Comment by hannestyden** [comment]
Cleaned up the tests and rebased.

Please review again. :bow:

/cc @bjk-soundcloud

**Comment by bjk-soundcloud** [comment]
Fantastic, thanks! :+1:

**Comment by arthurnn** [comment]
Add a changelog https://github.com/soundcloud/lhm/commit/771821caec22e3edd2e17e81427e0d1cd9040abf
thanks all.

**Pull request merged**
