### PR TITLE
Add test to check no line is forgotten when copying 5 lines with stride 2

### PR DESCRIPTION
**Pull request by tdeo**

### CODE REVIEW

**Comment by tdeo** [comment]
Anyway you could enable Travis build for PR? I can't manage to run the tests on my local machine, the script setup fails at 
```
bin/lhm-spec-setup-cluster.sh: line 64: ./*/mysql_install_db: No such file or directory
```
And I don't have more instructions

**Comment by tdeo** [comment]
@arthurnn this add a test I can't manage to run

**Comment by tdeo** [comment]
@arthurnn could you run that test someway ? To see if https://github.com/soundcloud/lhm/pull/127 is necessary

**Comment by tdeo** [comment]
@arthurnn I finally was able to [run this test on Travis](https://travis-ci.org/tdeo/lhm/jobs/201164311) on my fork and the test is failing

**Comment by nikonoll** [comment]
@tdeo you can fix `bin/lhm-spec-setup-cluster.sh: line 64: ./*/mysql_install_db: No such file or directory` by exchanging it with `which mysql_install_db` inside the script. At least on unix that should to the trick

**Pull request merged**
